# ===================================================================
# hostapd.conf — Punto de acceso WiFi
# SSID: Vpn | Password: RemixCli123
# Interfaz: wlx90de800944b6 (Realtek USB)
# ===================================================================
interface=wlx90de800944b6
driver=nl80211

# Red WiFi
ssid=Vpn
wpa_passphrase=RemixCli123

# Modo 802.11n (2.4GHz)
hw_mode=g
channel=6
ieee80211n=1

# Seguridad WPA2
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# Logs
logger_syslog=-1
logger_stdout=-1
